/*eslint-disable*/

import React, { useCallback, useEffect, useState } from "react";

export default function Modal ({
  isOpen,
  onClose,
  onSubmit,
  title,
  children,
  footer,
  buttonColor
}) {

  return (
    <>
      <div
        className="
          justify-center 
          items-center 
          flex 
          overflow-x-hidden 
          overflow-y-auto 
          fixed 
          inset-0 
          z-50 
          outline-none 
          focus:outline-none
          bg-slate-500
          bg-opacity-50
        "
      >
        <div
          className="
          relative 
          w-full
          md:w-4/6
          lg:w-3/6
          xl:w-2/5
          my-6
          mx-auto 
          h-full 
          lg:h-auto
          md:h-auto
          "
        >
          {/*content*/}
          <div
            className={`
            translate
            duration-300
            h-full
            ${isOpen ? "translate-y-0" : "translate-y-full"}
            ${isOpen ? "opacity-100" : "opacity-0"}
          `}
          >
            <div
              className="
              translate
              h-full
              lg:h-auto
              md:h-auto
              border-0 
              rounded-lg 
              shadow-lg 
              relative 
              flex 
              flex-col 
              w-full 
              bg-white 
              outline-none 
              focus:outline-none
            "
            >
              {/*header*/}
              <div
                className="
                flex 
                items-center 
                p-6
                rounded-t
                justify-center
                relative
                border-b-[1px]
                "
              >
                <div className="text-lg text-black font-semibold">{title}</div>
              </div>
              {/*body*/}
              <div className="text-black relative p-6 flex-auto">{children}</div>
              {/*footer*/}
              <div className="flex flex-col gap-2 p-6 border-t-[1px]">
                <div
                  className="
                    flex 
                    flex-row 
                    items-center 
                    gap-4 
                    w-full
                  "
                >
                  <button
                    className="
                      p-1
                      border-0 
                      hover:opacity-70
                      transition
                      text-red
                    "
                    onClick={onClose}
                  >
                    Cancel
                  </button>
                  <button
                    className={`
                      p-1
                      border-0 
                      hover:opacity-70
                      ${buttonColor}                      
                    `}
                    onClick={onSubmit}
                  >{footer}</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};